# Problem 72 - Counting fractions



Consider the fraction, n/d, where n and d are positive integers. If n<d and HCF(n,d)=1, it is called a reduced proper fraction.

If we list the set of reduced proper fractions for d ≤ 8 in ascending order of size, we get:

1/8, 1/7, 1/6, 1/5, 1/4, 2/7, 1/3, 3/8, 2/5, 3/7, 1/2, 4/7, 3/5, 5/8, 2/3, 5/7, 3/4, 4/5, 5/6, 6/7, 7/8

It can be seen that there are 21 elements in this set.

How many elements would be contained in the set of reduced proper fractions for d ≤ 1,000,000?


In [1]:
import numpy as np

In [2]:
?? np.gcd

In [3]:
from tqdm import tqdm

In [145]:
max_d = 10**2
fractions = []

for d in tqdm(range(1, max_d+1)):
    for n in range(1, d):
        if np.gcd(n, d) == 1:
            fractions.append((n, d))

100%|██████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 31103.48it/s]


In [146]:
len(fractions)

3043

In [44]:
import time

start = time.time()
for i in range(1123, 10123421400):
    np.gcd(i, 12112341898823432)

time.time() - start

KeyboardInterrupt: 

In [45]:
fractions

[(1, 2),
 (1, 3),
 (2, 3),
 (1, 4),
 (3, 4),
 (1, 5),
 (2, 5),
 (3, 5),
 (4, 5),
 (1, 6),
 (5, 6),
 (1, 7),
 (2, 7),
 (3, 7),
 (4, 7),
 (5, 7),
 (6, 7),
 (1, 8),
 (3, 8),
 (5, 8),
 (7, 8),
 (1, 9),
 (2, 9),
 (4, 9),
 (5, 9),
 (7, 9),
 (8, 9),
 (1, 10),
 (3, 10),
 (7, 10),
 (9, 10)]

In [66]:
from sympy import sieve, primefactors

In [74]:
start = time.time()

primes = list(sieve.primerange(1, 10**6))

time.time() - start

0.008040189743041992

In [73]:
start = time.time()

for i in range(1, 10**6):
    primefactors(i)
    
time.time() - start

13.064822912216187

In [75]:
primefactors(100)

[2, 5]

In [77]:
for i in range(8):
    for j in range(4):
        num = 2**i * 5**j
        if num <= 100:
            print(num)

1
5
25
2
10
50
4
20
100
8
40
16
80
32
64


In [78]:
l = []

for i in range(1, 101):
    if np.gcd(i, 100) == 1:
        l.append(i)
        
print(len(l))

40


In [ ]:
d_max = 10**6

In [12]:
m = np.zeros([d_max, d_max])
m

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
from sympy import sieve
import math

d_max = 11
m = np.zeros([d_max, d_max])
primes = list(sieve.primerange(1, d_max))

for d in range(2, d_max):
    if d not in primes:
        for n in range(1, d):
            if np.gcd(n, d) != 1:
                m[n-1, d-1] = 1
                for k in range(2, math.floor(d_max/d)):
                    m[k*n-1, k*d-1] = 1

In [9]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [83]:
np.tril(m).fill(1)

In [84]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
t = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

np.fill_diagonal(t[3:, :], 8)

In [71]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
def lower_triangular_filler(m, k):
    n = len(m)
    for i in range(n):
        np.fill_diagonal(m[i:, :], k)
    return m

In [73]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [83]:
lower_triangular_filler(m, 8)

array([[8., 0., 0., 0., 0., 0., 0., 0.],
       [8., 8., 0., 1., 0., 1., 0., 0.],
       [8., 8., 8., 0., 0., 1., 0., 0.],
       [8., 8., 8., 8., 0., 1., 0., 0.],
       [8., 8., 8., 8., 8., 0., 0., 0.],
       [8., 8., 8., 8., 8., 8., 0., 0.],
       [8., 8., 8., 8., 8., 8., 8., 0.],
       [8., 8., 8., 8., 8., 8., 8., 8.]])

Correct based on the example in notability

In [101]:
from sympy import sieve
import math

d_max = 8
m = np.zeros([d_max, d_max])
primes = list(sieve.primerange(1, d_max+1))

for d in range(2, d_max+1):
    if d not in primes:
        for n in range(1, d):
            if np.gcd(n, d) != 1:
                m[n-1, d-1] = 1
                for k in range(2, math.floor(d_max/d)):
                    m[k*n-1, k*d-1] = 1

In [102]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
1-m

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [104]:
new_m = lower_triangular_filler(1-m, 0)

In [105]:
sum(sum(new_m))

21.0

In [106]:
new_m

array([[0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

## Original

In [13]:
import time 
import math
import numpy as np
from sympy import sieve
from tqdm import tqdm

start = time.time()

d_max = 10**3
m = np.zeros([d_max, d_max])
primes = list(sieve.primerange(1, d_max+1))

def lower_triangular_filler(m, k):
    '''
        Fills matrix m with k under the diagonal
    '''
    n = len(m)
    for i in range(n):
        np.fill_diagonal(m[i:, :], k)
    return m

for d in tqdm(range(2, d_max+1)):
    if d not in primes:
        for n in range(1, d):
            if m[n-1, d-1] == 0:
                if np.gcd(n, d) != 1:
                    m[n-1, d-1] = 1
                    for k in range(2, math.floor(d_max/d)):
                        m[k*n-1, k*d-1] = 1

new_m = lower_triangular_filler(1-m, 0)
reduced_fractions = sum(sum(new_m))

print(reduced_fractions, time.time() - start)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 999/999 [00:00<00:00, 2463.67it/s]

304191.0 0.4141519069671631


## not Optimized

In [16]:
import time 
import math
import numpy as np
from sympy import sieve
from tqdm import tqdm

start = time.time()

d_max = 10**3
m = np.zeros([d_max, d_max])
primes = list(sieve.primerange(1, d_max+1))

visited_indices = []

def lower_triangular_filler(m, k):
    '''
        Fills matrix m with k under the diagonal
    '''
    n = len(m)
    for i in range(n):
        np.fill_diagonal(m[i:, :], k)
    return m

for d in tqdm(range(2, d_max+1)):
    if d not in primes:
        for n in range(1, d):
            if (n-1, d-1) not in visited_indices:
                if m[n-1, d-1] == 0:
                    if np.gcd(n, d) != 1:
                        m[n-1, d-1] = 1
                        visited_indices.append((n-1, d-1))
                        for k in range(2, math.floor(d_max/d)):
                            m[k*n-1, k*d-1] = 1
                            visited_indices.append((k*n-1, k*d-1))
                            
new_m = lower_triangular_filler(1-m, 0)
reduced_fractions = sum(sum(new_m))

print(reduced_fractions, time.time() - start)

 30%|██████████████████████████████▋                                                                         | 295/999 [00:19<00:45, 15.47it/s]


KeyboardInterrupt: 